name: seed_deck
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: any
  firebase_auth: any
  firebase_storage: any
  flutter_login: ^3.1.0
  cloud_functions: ^3.2.5
  qr_code_scanner: ^0.6.1
  cupertino_icons: ^1.0.1
  path_provider: any
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/yourlogo.png
  uses-material-design: true

